// <auto-generated />
using Actividad4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad4.Migrations
{
    [DbContext(typeof(PanaderiaContext))]
    partial class PanaderiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad4.Data.Panaderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Panaderias");
                });

            modelBuilder.Entity("Actividad4.Data.PanaderiaProducto", b =>
                {
                    b.Property<int>("PanaderiaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("PanaderiaId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PanaderiasProductos");
                });

            modelBuilder.Entity("Actividad4.Data.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Actividad4.Data.PanaderiaProducto", b =>
                {
                    b.HasOne("Actividad4.Data.Panaderia", "Panaderia")
                        .WithMany("PanaderiasProductos")
                        .HasForeignKey("PanaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Actividad4.Data.Producto", "Producto")
                        .WithMany("PanaderiasProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panaderia");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Actividad4.Data.Panaderia", b =>
                {
                    b.Navigation("PanaderiasProductos");
                });

            modelBuilder.Entity("Actividad4.Data.Producto", b =>
                {
                    b.Navigation("PanaderiasProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
